#Map Size
TrajRoll/MAP_WIDTH:            1280
TrajRoll/MAP_HEIGHT:           720
TrajRoll/RESOLUTION:           0.0039

#Trajectory Generation Parameters
TrajRoll/NUM_PATHS:            13
TrajRoll/TRAJECTORY_STEPS:     20
TrajRoll/MIN_STOPPING_DIST:    0.2
TrajRoll/STOPPING_FACTOR:      0.15

#Desired Velocity Setup
TrajRoll/STRAIGHT_SPEED:       3.0

#Vehicle Parameters
TrajRoll/MAX_STEERING_ANGLE:   0.4
TrajRoll/CAR_WIDTH:            0.15
TrajRoll/DIST_REWARD_FACTOR:   2.0
TrajRoll/MIN_OFFSET_DIST:      0.05

#For Debugging 
#Visualization
TrajRoll/VISUALIZATION:        true
TrajRoll/DEBUG_ON:             false
