%YAML:1.0

# 4 point coordinates in image plane used as the source coordinates for the warp transform
# Note: OpenCV Image coordinates are in [x,y], where X is a column index 
# (0 left, positive rightwards), and Y is a row index (0 top, positive downwards)
warp_src_coords: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [500, 350, 750, 350, 1280, 550, 0, 450]

min_contour_size: 250

resolution: 0.0045

camera_feed: 'right'

camera_width_offset: 0.05
camera_height_offset: 0.048